### ISSUE TITLE
List of issues when following Introduction to the Unix shell tutorial using `Git Bash` on Windows 10

### ISSUE THREAD

**Issue by amartinhuertas** [MonashMath/SCI1022#4]
* Section 1.1.2. Instructions for running a terminal are for MoVe + Cygwin. Replace by instructions for Git+Bash, Unix and MacOSx.
* Section 1.1.3. After Exercise 2. `man` command not available for Git+Bash. Alternatives: `--help` or man pages available on the internet. Note: `echo --help` does not work. Replace `echo` by `cat` in the example when looking for help.
* Section 1.1.3. After Exercise 3, rest of the section cannot be followed. `man` not available. 
* Section 1.1.4. `Ctrl-A` does not work: It is handled by the Git+Bash window, and not by `bash`. 
* Section 1.1.4. Exercise 5. Cannot be done. `man` not available.
* Section 1.1.6. Note: `tree` command not available.
* Section 1.2.1. Two notes on how to Copy & Paste refer to MoVe + Cygwin. Update comment.  Ctrl+C/Ctrl+V can be used on Git+Bash.
* Section 1.3.1. Remove Hint from Exercise 14.
* Section 1.3.1. In Git+Bash the home directory is not located at `/home`, but at `/c/Users/name_of_user`. Thus, Exercise 15 cannot be done.
* Section 1.3.1. Note on Move OUT. 
* Section 1.3.1. Exercise 18. The `/etc` system directory is writable by the working user. 
* Section 1.3.1. Exercise 19. Requires man, but can be solved with `--help`.
* Section 1.3.3. Concern: most of the contents/examples of the section refer to `/home`. Can be confusing in Git+Bash, although it can be followed if u know what u are doing. 
* Section 1.3.4. Exercise 26. `tree not available`.
* Section 1.4.1. `top`, `uptime` not available. `finger` exists but does not make sense.
* Section 1.4.1. Note on move also applies to Git+Bash, but has to be rewritten.
* Section 1.4.1. Exercise 27 returns `cannot find name for group ID 197121`. Seems that Git+Bash does not handle the translation of group IDs into group names.
* Section 1.4.2. Permissions. The majority of commands to change the permissions do not have effect at all. One can only add/remove write permission to the user. The `chmod` command does not have any affect on the permissions for the group and all.  
* Section 1.4.2. Exercise 30, 31 and 32 cannot be done because of the same reason as in the above point.
* Section 1.5.1. Reference to MoVE. remove "which is installed along with the Cygwin APP in MoVE."
* Section 1.5.4. `less`. `Ctrl+F` does not work ... you have to use `F`. The rest of Ctrl+ combinations work.
* Section 1.5.4. Clarify that the `/` option is to be used within the interactive mode of `less`, i.e., it is not a command-line flag to be passed to the command.

**Comment by santiagobadia** [comment]
Alberto what is the copy paste in git-shell?

**Comment by santiagobadia** [comment]
Questions that arise:

* Not sure about Ex. 15 issue. I would say that the section itself needs to change things, and Ex 15 still has sense, but I am probably wrong
* I would probably move Tab completion to the beginning, it will be very useful during the session

**Comment by amartinhuertas** [comment]
Dont forget to update the PDFs once we have finished this page.

**Comment by santiagobadia** [comment]
Closing issue
